import type { editor } from 'monaco-editor';

/** Tokyo Night 主题 — 适配 Monaco Editor */
export const TOKYO_NIGHT_THEME: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'c0caf5', background: '1a1b26' },
    { token: 'comment', foreground: '565f89', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'bb9af7' },
    { token: 'keyword.control', foreground: 'bb9af7' },
    { token: 'keyword.operator', foreground: '89ddff' },
    { token: 'keyword.other', foreground: 'bb9af7' },
    { token: 'storage', foreground: 'bb9af7' },
    { token: 'storage.type', foreground: 'bb9af7' },
    { token: 'type', foreground: '7dcfff' },
    { token: 'type.identifier', foreground: '7dcfff' },
    { token: 'string', foreground: '9ece6a' },
    { token: 'string.quoted', foreground: '9ece6a' },
    { token: 'number', foreground: 'ff9e64' },
    { token: 'constant', foreground: 'ff9e64' },
    { token: 'constant.numeric', foreground: 'ff9e64' },
    { token: 'constant.language', foreground: 'ff9e64' },
    { token: 'variable', foreground: 'c0caf5' },
    { token: 'variable.parameter', foreground: 'e0af68' },
    { token: 'function', foreground: '7aa2f7' },
    { token: 'function.declaration', foreground: '7aa2f7' },
    { token: 'method', foreground: '7aa2f7' },
    { token: 'tag', foreground: 'f7768e' },
    { token: 'attribute.name', foreground: '9ece6a' },
    { token: 'attribute.value', foreground: '89ddff' },
    { token: 'delimiter', foreground: '565f89' },
    { token: 'delimiter.bracket', foreground: 'c0caf5' },
    { token: 'delimiter.parenthesis', foreground: 'c0caf5' },
    { token: 'invalid', foreground: 'f7768e', background: '1a1b26' },
    { token: 'meta.embedded', foreground: 'c0caf5' },
  ],
  colors: {
    'editor.background': '#1a1b26',
    'editor.foreground': '#c0caf5',
    'editor.lineHighlightBackground': '#1f2335',
    'editor.selectionBackground': '#3b4261',
    'editor.inactiveSelectionBackground': '#2c304a',
    'editorCursor.foreground': '#c0caf5',
    'editorWhitespace.foreground': '#3b4261',
    'editorLineNumber.foreground': '#3b4261',
    'editorLineNumber.activeForeground': '#6b7390',
    'editorIndentGuide.background': '#252937',
    'editorIndentGuide.activeBackground': '#3b4261',
    'editor.selectionHighlightBackground': '#2c304a',
    'editorBracketMatch.background': '#2c304a',
    'editorBracketMatch.border': '#565f89',
    'editorOverviewRuler.border': '#1a1b26',
    'editorGutter.background': '#1a1b26',
    'editorWidget.background': '#1f2335',
    'editorWidget.border': '#252937',
    'input.background': '#1a1b26',
    'input.border': '#252937',
    'input.foreground': '#c0caf5',
    'scrollbar.shadow': '#00000033',
    'scrollbarSlider.background': '#3b426180',
    'scrollbarSlider.hoverBackground': '#3b4261',
    'scrollbarSlider.activeBackground': '#565f89',
    'badge.background': '#252937',
    'badge.foreground': '#c0caf5',
    'button.background': '#2f354a',
    'button.foreground': '#c0caf5',
    'button.hoverBackground': '#3b4261',
    'dropdown.background': '#1f2335',
    'dropdown.border': '#252937',
    'menu.background': '#1f2335',
    'menu.foreground': '#c0caf5',
    'menu.selectionBackground': '#3b4261',
    'menu.separatorBackground': '#252937',
    'minimap.background': '#1a1b26',
    'minimapSlider.background': '#3b426180',
    'minimapSlider.hoverBackground': '#3b4261',
    'minimapSlider.activeBackground': '#565f89',
    'panel.background': '#1a1b26',
    'panel.border': '#252937',
    'panelTitle.activeForeground': '#c0caf5',
    'panelTitle.inactiveForeground': '#565f89',
    'peekView.background': '#1f2335',
    'peekView.border': '#252937',
    'peekViewTitle.background': '#1f2335',
    'peekViewResult.background': '#1f2335',
    'peekViewResult.selectionBackground': '#3b4261',
    'statusBar.background': '#1a1b26',
    'statusBar.foreground': '#c0caf5',
    'statusBar.border': '#252937',
    'tab.activeBackground': '#1a1b26',
    'tab.activeForeground': '#c0caf5',
    'tab.inactiveBackground': '#1f2335',
    'tab.inactiveForeground': '#565f89',
    'tab.border': '#252937',
    'tab.activeBorder': '#7aa2f7',
    'titleBar.activeBackground': '#1a1b26',
    'titleBar.activeForeground': '#c0caf5',
    'titleBar.inactiveBackground': '#1f2335',
    'titleBar.inactiveForeground': '#565f89',
  },
};
